# Generated by Django 3.1.7 on 2021-03-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_trading.asset_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('power_of_10', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_sell', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1)),
                ('status', models.CharField(choices=[('O', 'Open'), ('F', 'Fulfilled'), ('C', 'Cancelled')], default='O', max_length=1)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.athlete')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.entity')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.club'),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trading.asset')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.athlete')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.entity')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('trading.asset',),
        ),
    ]
