# Generated by Django 3.1.7 on 2021-04-17 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20210416_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest_interval',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='lender',
        ),
        migrations.CreateModel(
            name='LoanPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Fractional interest rate', max_digits=10)),
                ('interest_interval', models.DurationField(default=datetime.timedelta(7))),
                ('max_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_loanpolicy_lender', to='trading.entity')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.loanpolicy'),
            preserve_default=False,
        ),
    ]
