# Generated by Django 3.1.7 on 2021-04-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20210417_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='future',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.future'),
        ),
        migrations.AddField(
            model_name='trade',
            name='future',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.future'),
        ),
    ]
