# Generated by Django 3.1.7 on 2021-04-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_order_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="unfilled_volume",
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("O", "Open"),
                    ("F", "Fulfilled"),
                    ("P", "Partially filled"),
                    ("C", "Cancelled"),
                ],
                default="O",
                max_length=1,
            ),
        ),
    ]
