# Generated by Django 3.1.7 on 2021-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20210418_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='actioned',
            field=models.BooleanField(default=False),
        ),
    ]
