# Generated by Django 3.1.7 on 2021-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20210401_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='traded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='volume',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
