# Generated by Django 3.1.7 on 2021-04-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20210402_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='traded_at',
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.athlete')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_trade_buyer', to='trading.entity')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_trade_seller', to='trading.entity')),
            ],
        ),
    ]
