# Generated by Django 3.1.7 on 2021-04-18 20:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_trade_actioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='closes',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 18, 35, 737139, tzinfo=utc)),
        ),
    ]
