# Generated by Django 3.1.7 on 2021-04-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0008_dividend"),
    ]

    operations = [
        migrations.RemoveField(model_name="dividend", name="athlete",),
        migrations.RemoveField(model_name="dividend", name="race",),
        migrations.AddField(
            model_name="dividend",
            name="result",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trading_dividend_result",
                to="trading.result",
            ),
            preserve_default=False,
        ),
    ]
